import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Image, Box, Button, Input } from '@chakra-ui/react'
import { useState } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [files, setFiles] = useState('value');

  const postImage = async (event) => {
    event.preventDefault();
    let formData = new FormData();
    for(let i = 0; i < files.length; i++) {
      formData.append('files', files[i]);
    }

    try {
      const res = await fetch("http://127.0.0.1:8082/detect-people-photo", {
        method: "POST",
        body: formData
      });
      const data = await res.json();
      console.log('ssss', files)
      console.log('\nDATA\n', data);
    } catch (err) {
      console.log('\n ERROR \n', err);
    }
  }

  const postVideo = async (event) => {
    event.preventDefault();
    let formData = new FormData();
    for(let i = 0; i < files.length; i++) {
      formData.append('files', files[i]);
    }

    try {
      const res = await fetch("http://127.0.0.1:8082/detect-people-video", {
        method: "POST",
        body: formData
      });
      const data = await res.json();
      console.log('ssss', files)
      console.log('\nDATA\n', data);
    } catch (err) {
      console.log('\n ERROR \n', err);
    }
  }
  
  const handleInput = async (event) => {
    setFiles(event.target.files);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Box boxSize='sm'>
          <Image src='https://e7.pngegg.com/pngimages/476/159/png-clipart-pokemon-pikachu-pikachu-pokemon-games-pokemon-thumbnail.png' alt='Dan Abramov' />
          <form onSubmit={ postImage } method='post'>
            <Input
              placeholder="Upload media"
              size="md"
              type="file"
              onChange={(e) =>  handleInput(e) }
              multiple
            />
            <Button colorScheme='blue' type='submit'>Upload Images</Button>
          </form>
          <form onSubmit={ postVideo } method='post'>
            <Input
              placeholder="Upload Video"
              size="md"
              type="file"
              onChange={(e) =>  handleInput(e) }
              multiple
            />
            <Button colorScheme='blue' type='submit'>Upload Video</Button>
          </form>
        </Box>
      </main>
    </>
  )
}
